#!/usr/bin/env node
/**
 * Font layer generator — brief #9 "The Type Program".
 * Rebuilds src/ui/styles/fonts.css from the pinned @fontsource packages
 * (versions locked by pnpm-lock.yaml). The base64 payload is MACHINE-WRITTEN —
 * never hand-edit fonts.css (same discipline as src/content/generated).
 *
 * Usage: node tools/build-fonts.mjs
 *
 * Why data-URIs: the single-file artifact must be self-contained (offline
 * Tauri later, zero runtime network), and the style-layer guard already
 * requires every url() in src/ui/styles to be a data: URI.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = join(repoRoot, 'src', 'ui', 'styles', 'fonts.css');

/** Latin unicode-range as served by Google Fonts / @fontsource. */
const LATIN =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, ' +
  'U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

/** The hired faces — weights match actual usage in the style layer. */
const FACES = [
  // Alegreya: the text voice (--gv-serif). 400 body · 600 heads · 700 bold · 400 italic (marginalia, sea names).
  { pkg: '@fontsource/alegreya', family: 'Alegreya', file: 'alegreya-latin-400-normal.woff2', weight: 400, style: 'normal' },
  { pkg: '@fontsource/alegreya', family: 'Alegreya', file: 'alegreya-latin-400-italic.woff2', weight: 400, style: 'italic' },
  { pkg: '@fontsource/alegreya', family: 'Alegreya', file: 'alegreya-latin-600-normal.woff2', weight: 600, style: 'normal' },
  { pkg: '@fontsource/alegreya', family: 'Alegreya', file: 'alegreya-latin-700-normal.woff2', weight: 700, style: 'normal' },
  // Alegreya Sans SC: the label/plate voice (--gv-sans). 500 labels · 700 plates/ledger heads · 800 stamps.
  { pkg: '@fontsource/alegreya-sans-sc', family: 'Alegreya Sans SC', file: 'alegreya-sans-sc-latin-500-normal.woff2', weight: 500, style: 'normal' },
  { pkg: '@fontsource/alegreya-sans-sc', family: 'Alegreya Sans SC', file: 'alegreya-sans-sc-latin-700-normal.woff2', weight: 700, style: 'normal' },
  { pkg: '@fontsource/alegreya-sans-sc', family: 'Alegreya Sans SC', file: 'alegreya-sans-sc-latin-800-normal.woff2', weight: 800, style: 'normal' },
  // Atkinson Hyperlegible: readable type (body.gv-readable swaps both tokens here).
  { pkg: '@fontsource/atkinson-hyperlegible', family: 'Atkinson Hyperlegible', file: 'atkinson-hyperlegible-latin-400-normal.woff2', weight: 400, style: 'normal' },
  { pkg: '@fontsource/atkinson-hyperlegible', family: 'Atkinson Hyperlegible', file: 'atkinson-hyperlegible-latin-400-italic.woff2', weight: 400, style: 'italic' },
  { pkg: '@fontsource/atkinson-hyperlegible', family: 'Atkinson Hyperlegible', file: 'atkinson-hyperlegible-latin-700-normal.woff2', weight: 700, style: 'normal' },
];

const face = ({ pkg, family, file, weight, style }) => {
  const bytes = readFileSync(join(repoRoot, 'node_modules', pkg, 'files', file));
  return `/* ${file} — ${(bytes.length / 1024).toFixed(1)} KiB */
@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  unicode-range: ${LATIN};
  src: url(data:font/woff2;base64,${bytes.toString('base64')}) format('woff2');
}`;
};

const css = `/**
 * GENERATED by tools/build-fonts.mjs — DO NOT EDIT BY HAND. Regenerate: node tools/build-fonts.mjs
 * Brief #9 type program: Alegreya (text) · Alegreya Sans SC (labels) · Atkinson Hyperlegible (readable type).
 * All faces SIL OFL via @fontsource (versions pinned in pnpm-lock.yaml). Latin subset only.
 */
${FACES.map(face).join('\n')}
`;

writeFileSync(outPath, css);
const kib = (css.length / 1024).toFixed(0);
console.log(`[build-fonts] wrote ${outPath} (${kib} KiB, ${FACES.length} faces)`);
