#!/usr/bin/env node
/**
 * Content converter — machine-converts game_data.db into TS registries.
 * NEVER retype content by hand (decision-ledger Area 6): silent corruption of
 * hand-tuned balance data is the #1 migration risk this tool exists to prevent.
 *
 * Usage: node tools/convert-content.mjs [path-to-game_data.db]
 *
 * Gates: EXPECTED_COUNTS below must match exactly, or the converter exits 1.
 * When content legitimately grows, update the gate in the same commit.
 */
import Database from 'better-sqlite3';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const dbPath = process.argv[2] ?? join(repoRoot, '..', 'GuildVigil', 'project', 'data', 'game_data.db');
const outDir = join(repoRoot, 'src', 'content', 'generated');

// Hard gates on the tables whose hand-tuned values are irreplaceable.
const EXPECTED_COUNTS = {
  spells: 218,
  feats: 227,
  class_progression: 230,
  class_proficiency_tiers: 112,
  items: 183,
  item_properties: 33,
  enemies: 24,
  classes: 13,
  ancestries: 6,
  skills: 15,
  class_skills: 64,
  class_weapon_proficiency: 44,
  loot_tables: 97,
  shop_stock: 105,
  buildings: 18,
  quests: 12,
  warlock_spell_costs: 7,
  bloodlines: 8,
  bloodline_spells: 40,
  legendary_scholars: 28,
  nations: 9,
  nation_leaders: 35,
  eight_pillars: 8,
};

// Empty-by-design tables (narrative layer, populated later) — converted but ungated.
const KNOWN_EMPTY_OK = new Set([
  'factions', 'lore_references', 'npc_combat_data', 'npc_preferences', 'npcs',
  'story_dialogue', 'story_heroes', 'storyline_quests', 'storylines',
  'class_prerequisites', 'world_regions',
]);

const db = new Database(dbPath, { readonly: true });
const tables = db
  .prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
  .all()
  .map((r) => r.name);

mkdirSync(outDir, { recursive: true });

const manifest = {};
const failures = [];

for (const table of tables) {
  const rows = db.prepare(`SELECT * FROM "${table}"`).all();
  manifest[table] = rows.length;

  const expected = EXPECTED_COUNTS[table];
  if (expected !== undefined && rows.length !== expected) {
    failures.push(`${table}: expected ${expected}, got ${rows.length}`);
  }
  if (expected === undefined && !KNOWN_EMPTY_OK.has(table) && rows.length === 0) {
    failures.push(`${table}: unexpectedly empty and not in KNOWN_EMPTY_OK`);
  }

  const banner = `// GENERATED by tools/convert-content.mjs from game_data.db — DO NOT EDIT BY HAND.\n// Regenerate: pnpm convert\n`;
  writeFileSync(
    join(outDir, `${table}.ts`),
    `${banner}export const ${table} = ${JSON.stringify(rows, null, 1)} as const;\n`,
  );
}

writeFileSync(
  join(outDir, 'manifest.ts'),
  `// GENERATED — row counts at conversion time, consumed by the count-gate test.\n` +
    `export const CONTENT_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;\n`,
);

writeFileSync(
  join(outDir, 'index.ts'),
  `// GENERATED barrel.\n` + tables.map((t) => `export { ${t} } from './${t}';`).join('\n') +
    `\nexport { CONTENT_MANIFEST } from './manifest';\n`,
);

if (failures.length > 0) {
  console.error('COUNT GATE FAILURES:');
  for (const f of failures) console.error(`  ${f}`);
  process.exit(1);
}

console.log(`Converted ${tables.length} tables from ${dbPath}`);
console.log(Object.entries(manifest).map(([t, n]) => `  ${t}: ${n}`).join('\n'));
